<a href="https://colab.research.google.com/github/PingPingE/Learn_ML_DL/blob/main/Hands_On_ML/ch12-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서플로우
- 구글 브레인에서 개발(2015년 11월 공개)
- 강력한 수치 계산용 라이브러리

## 제공하는 것
1. 핵심 구조는 numpy와 비슷하지만, <strong>GPU 지원</strong>
2. 여러 장치와 서버에 대해 <strong>분산 컴퓨팅</strong> 지원
3. JIT(Just In Time)컴파일러 포함 : <strong>속도를 높이고 메모리 사용량을 줄여준다.</strong>

  과정) 파이썬 함수에서 <strong>계산 그래프</strong>를 추출 ->  최적화(사용하지 않는 노드 가지치기) -> 효율적으로 실행(ex)<strong>독립적인 연산을 자동으로 병렬 실행</strong>)

4. 계산 그래프는 <strong>플랫폼에 중립적인 포맷</strong>으로 내보낼 수 있다.(ex) 리눅스에서 파이썬으로 훈련하고 안드로이드의 자바에서 실행)
5. <strong>자동 미분(auto diff)</strong>기능과 RMSProp, Nadam과 같은 <strong>고성능 옵티마이저</strong>를 제공한다.


참고 [링크](https://medium.com/@ljb7977/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0-2-0%EC%97%90%EC%84%9C-%EB%8B%AC%EB%9D%BC%EC%A7%80%EB%8A%94-%EC%A0%90-6e233e0c7fbe)


![](https://miro.medium.com/proxy/0*fJ5u2WE51Oz44dr_)

# 넘파이처럼 텐서플로 이용하기
- 텐서플로 API는 tensor를 순환시킨다.
- tensor는 한 연산에서 다른 연산으로 흐른다. 그래서 tensorflow
- tensor는 numpy의 ndarray와 매우 비슷하다.
- tensor는 일반적으로 다차원 배열(하지만 스칼라 값도 가질 수 있음)
- 사용자가 직접 정의하는 손실함수, 지표, 네트워크 등을 만들 때 텐서가 중요하다.

### 텐서와 연산
- tf. constant()함수로 텐서를 만들 수 있다.

In [ ]:
import tensorflow as tf

In [ ]:
tf.constant([[1.,2.,3.], [4.,5.,6.]]) 

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

#### 정보 확인(shape, dtype)

In [ ]:
t= tf.constant([[1.,2.,3.],[4.,5.,6.]])
#크기
t.shape

TensorShape([2, 3])

In [ ]:
t.dtype #데이터 타입

tf.float32

#### 참조 및 채널 차원 추가

In [ ]:
t[:, 1:] #인덱스 참조

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [ ]:
t[...,1,tf.newaxis] #채널 차원 추가

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [ ]:
t[:,1,tf.newaxis]#...대신 :해도 똑같다

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

#### 모든 종류의 텐서 연산 가능(numpy와 이름이 비슷)

  add, multiply, square, exp, sqrt, reshape, squeeze, tile 등

  단, 일부 함수(reduce_mean, reduce_sum, reduce_max, math.log = numpy의 mean, sum, max, log와 동일하다)
<br><br>

  *reduce가 붙는 이유: GPU커널이 원소가 추가된 <strong>순서를 보장하지 않는 reduce알고리즘</strong>을 사용하기 때문 
  
  -> 그래서 순서가 결과에 영향을 미치지 않는 연산에만 reduce가 붙어있네

In [ ]:
t+10 #scalar와 연산 -> broadcasting

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.add(t,10)  #= t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
t@tf.transpose(t) #행렬 곱셈(=tf.matmul())

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

#### transpose: tf.transpose(t)로 해야함.(t.T 안된다)

=> numpy는 t.T하면 전치된 view가 나오고, tensorflow는 tf.transpose(t)하면 전치된 새로운 텐서가 나온다.

In [ ]:
trans_t = tf.transpose(t)
trans_t

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [ ]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

## 텐서와 넘파이

- 텐서는 넘파이와 함께 사용하기 편하다.
- 넘파이 배열로 텐서를 만들 수 있고, 그 반대도 가능하다.
- 넘파이 배열에 텐서플로 연산을 적용할 수 있고, 그 반대도 가능하다.
- 넘파이는 기본으로 64비트 정밀도를 사용하지만 텐서플로는 32비트 정밀도를 사용한다.

*일반적으로 신경망은 32비트 정밀도로 충분하고 더 빠르고 메모리도 적게 사용하기 때문

(넘파이 배열로 텐서를 만들 때는 dtype=tf.float32로 지정해야한다.

부동소수점 관련 [링크](https://gsmesie692.tistory.com/94)

#### numpy -> tensor

In [ ]:
import numpy as np
a = np.array([2.,4.,5.])
tf.constant(a)


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [ ]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=float64, numpy=11.0>

#### tensor -> numpy

In [ ]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [ ]:
np.sum(t)

21.0

In [ ]:
np.log(t)

array([[0.       , 0.6931472, 1.0986123],
       [1.3862944, 1.609438 , 1.7917595]], dtype=float32)

## 타입 변환
타입 변환은 성능을 크게 감소시킬 수 있다.

텐서플로는 타입 변환을 자동으로 수행하지 않는다.
- 그래서 <strong>호환되지 않는 타입의 텐서</strong>로 연산을 수행하면 예외가 발생

ex) 실수 텐서 + 정수 텐서 X

32비트 실수 + 64비트 실수 X

In [ ]:
tf.constant(4.) - tf.constant(5)

InvalidArgumentError: ignored

In [ ]:
tf.constant(2.) - tf.constant(4. ,dtype=tf.float64)

InvalidArgumentError: ignored

- 만약 타입 변환이 진짜로 필요하다면 -> tf.cast()

In [ ]:
t2= tf.constant(40, dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2 ,dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

## 변수

- <strong>tf.Tensor는 내용을 바꿀 수 없는 객체</strong>이다.

### 하지만 내용을 바꿔야 한다면? 
- 역전파로 변경되어야 하는 신경망의 가중치라던지, 
- 시간에 따라 변경되야하는 모멘텀 옵티마이저(과거 gradient를 계속 업뎃)를 사용하는 경우

=> <strong>tf.Variable</strong>이 필요한 이유

tf..Variable은 tf.Tensor와 비슷하게 동작한다. 동일한 연산으로 수행할 수 있고 넘파이와도 잘 호환된다.

- <strong>assign()메서드</strong>를 사용하여 변숫값을 바꿀 수 있다.
- 단, tf.Variable은 tf.Tensor를 사용해서 값을 저장한다. 그래서 변수의 값을 변경하면 <strong>새로운 Tensor</strong>가 만들어 지는 것이다.

In [ ]:
v = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [ ]:
v[0,1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [ ]:
v[:,1].assign([32,32])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 32.,  6.],
       [ 8., 32., 12.]], dtype=float32)>

In [ ]:
v.scatter_nd_update([[0,0],[1,1]], updates=[77,70])#개별 원소(또는 슬라이스) 수정

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[77., 32.,  6.],
       [ 8., 70., 12.]], dtype=float32)>

## 다른 데이터 구조

텐서플로는 다음과 같은 몇 가지 다른 데이터 구조도 지원한다.
- <strong>희소 텐서(sparse tensor)</strong> -> tf.SparseTensor: <strong>대부분 0으로 채워진 텐서</strong>를 효율적으로 나타낸다. 
- <strong>텐서 배열(tensor array)</strong> -> tf.TensorArray: <strong>텐서의 리스트</strong>이다. 기본적으로 고정된 길이를 가지지만 동적으로 바꿀 수 있다. 리스트에 포함된 모든 텐서는 크기와 데이터 타입이 동일해야한다.
- <strong>래그드 텐서(ragged tensor)</strong> -> tf.RaggedTensor: 래그드 텐서는 <strong>리스트의 리스트</strong>를 나타낸다. 텐서에 포함된 값은 동일한 데이터 타입을 가져야 하지만 리스트의 길이는 다를 수 있다.
- <strong>문자열 텐서(string tensor)</strong> -> tf.string 기본 데이터 타입의 텐서이다. 유니코드가 아닌 <strong>바이트 문자열</strong>을 나타낸다. (문자열 텐서를 만들면 자동으로 UTF-8로 인코딩된다)
- <strong>집합</strong> -> tf.sets 패키지의 연산으로 다룬다. 일반적인 텐서(또는 희소 텐서)로 나타낸다. 예를 들면 tf.constant([[1,2],[3,4]])는 두 개의 집합 {1,2}와 {3,4}를 나타낸다. 
- <strong>큐</strong>->tf.queue패키지의 연산으로 다룬다. 단계별로 텐서를 저장한다. 텐서플로는 여러 종류의 큐를 제공한다. 간단한 FIFO 큐, Prioirity 큐, 원소를 섞는 큐(RandomShuffle Queue), 패딩을 추가하여 크기가 다른 원소의 배치를 만드는 큐(PaddingFIFOQueue) 등이 있다. 

# 사용자 정의 모델과 훈련 알고리즘

##### 데이터 & 모델 준비

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
housing = fetch_california_housing()

In [ ]:
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)

In [ ]:
X_train.shape

(11610, 8)

In [ ]:
y_train.shape

(11610,)

In [ ]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.fit_transform(X_valid)
X_test = scaler.transform(X_test)

In [ ]:
from tensorflow import keras

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(10,activation='selu', kernel_initializer='lecun_normal', input_shape=X_train.shape[1:]))
# model.add(keras.layers.Dense(30,activation='selu', kernel_initializer='lecun_normal'))
model.add(keras.layers.Dense(1))

In [ ]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_31 (Dense)             (None, 10)                90        
_________________________________________________________________
dense_32 (Dense)             (None, 1)                 11        
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


#### 사용자 정의 손실 함수
 훈련세트에 잡음 데이터가 있다면? -> 이상치를 제거하는 건 비효율적(다 제거된다는 보장도 無)
- 평균 제곱 오차(MSE): 큰 오차에 너무 과한 벌칙
- 평균 절댓값 오차(MAE): 이상치에 관대해서 수렴하기 까지 시간이 오래걸림

==> 후버 손실을 사용하면 좋다.


*후버 손실: MSE와 MAE를 절충한 손실함수로, 오차가 특정 구간안이면 제곱, 아니면 절댓값

In [ ]:
def huber_fn(y_true, y_pred):
  error= y_true-y_pred
  is_small_error = tf.abs(error)<1 #기준(-1~1)
  squared_loss = tf.square(error)/2 
  linear_loss = tf.abs(error)-0.5
  return tf.where(is_small_error, squared_loss, linear_loss)#오차가 -1~1사이면 MSE, 아니면 MAE

----------------
전체 손실 평균이 아니라, 샘플마다 하나의 손실을 담은 텐서를 반환하는 것이 좋다. -> 
클래스 가중치나 샘플 가중치를 적용하기 위해

In [ ]:
model.compile(loss=huber_fn, optimizer='nadam')
model.fit(X_train, y_train,batch_size=128, epochs=10, validation_data=(X_valid, y_valid))

Epoch 1/10
91/91 [==============================] - 1s 3ms/step - loss: 1.5238 - val_loss: 1.1627
Epoch 2/10
91/91 [==============================] - 0s 2ms/step - loss: 0.9426 - val_loss: 0.6064
Epoch 3/10
91/91 [==============================] - 0s 2ms/step - loss: 0.4817 - val_loss: 0.3196
Epoch 4/10
91/91 [==============================] - 0s 2ms/step - loss: 0.2862 - val_loss: 0.2366
Epoch 5/10
91/91 [==============================] - 0s 2ms/step - loss: 0.2367 - val_loss: 0.2104
Epoch 6/10
91/91 [==============================] - 0s 2ms/step - loss: 0.2302 - val_loss: 0.2051
Epoch 7/10
91/91 [==============================] - 0s 2ms/step - loss: 0.2147 - val_loss: 0.2159
Epoch 8/10
91/91 [==============================] - 0s 2ms/step - loss: 0.2143 - val_loss: 0.2384
Epoch 9/10
91/91 [==============================] - 0s 4ms/step - loss: 0.2125 - val_loss: 0.2369
Epoch 10/10
91/91 [==============================] - 0s 2ms/step - loss: 0.2101 - val_loss: 0.2551


##### 사용자 정의 요소(여기선 huber 손실)를 가진 모델을 저장하고 로드하기

In [ ]:
model.save('model.h5')

In [ ]:
model2 = keras.models.load_model('model.h5')

ValueError: ignored

--------------
그냥 불러오면 위처럼 huber_fn을 모른다는 error가 뜬다.

In [ ]:
model2 = keras.models.load_model('model.h5', custom_objects={'huber_fn':huber_fn}) #custom_objects추가

In [ ]:
model2. summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_31 (Dense)             (None, 10)                90        
_________________________________________________________________
dense_32 (Dense)             (None, 1)                 11        
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


##### 특정 오차를 지정해서 사용하고 싶을 때 -> 매개변수 생성

In [ ]:
def create_huber(threshold=1.0):#default는 1.0
  def huber_fn(y_true, y_pred):
    error= y_true-y_pred
    is_small_error = tf.abs(error)<threshold
    squared_loss = tf.square(error)/2
    linear_loss = threshold*tf.abs(error)-threshold**2/2
    return tf.where(is_small_error, squared_loss, linear_loss)
  return huber_fn

In [ ]:
model2= keras.models.load_model('model.h5', custom_objects={'huber_fn':create_huber(2.0)})

----------------
- 기존에 저장된 손실함수 이름이 'huber_fn'이어서 여기도 그런 것이다
- threshold값은 같이 저장이 안된다.

##### Loss클래스 상속하고 get_config()메서드 구현하기

In [ ]:
class HuberLoss(keras.losses.Loss):
  def __init__(self, threshold=1.0,**kwargs):
    self.threshold = threshold
    super().__init__(**kwargs)

  def call(self, y_true, y_pred):
    error= y_true-y_pred
    is_small_error = tf.abs(error)<threshold
    squared_loss = tf.square(error)/2
    linear_loss = threshold*tf.abs(error)-threshold**2/2
    return tf.where(is_small_error, squared_loss, linear_loss)

  def get_config(self): #하이퍼파라미터 이름과 같이 매핑된 딕셔너리 반환
    base_config=super().get_config()
    return {**base_config, 'threshold':self.threshold}

In [ ]:
model.compile(loss=HuberLoss(2.), optimizer='nadam')

In [ ]:
model.save('model2.h5')

In [ ]:
model3 = keras.models.load_model('model2.h5', custom_objects={'HuberLoss':HuberLoss})

---------------
- 모델을 저장할 때 threshold값도 같이 저장된다.
- 로드할 때 클래스 이름과 클래스 자체를 매핑해주면 된다.

In [ ]:
model3.loss.get_config()

{'name': None, 'reduction': 'auto', 'threshold': 2.0}

#### 활성화 함수, 초기화, 규제, 제한을 커스터마이징하기
- 손실, 규제, 제한, 초기화, 지표, 활성화 함수, 층, 모델과 같은 대부분의 케라스 기능은 유사한 방법으로 커스터마이징할 수 있다.


In [ ]:
def my_softplus(z):
  return tf.math.log(tf.exp(z)+1.0)

def my_glorot_initializer(shape, dtype=tf.float32):
  stddev= tf.sqrt(2. / (shape[0] + shape[1]))
  return tf.random.normal(shape, stddev=stddev, dtype = dtype)

def my_l1_regularization(weights):#keras.regularizers.l1(0.01)과 동일
  return tf.reduce_sum(tf.abs(0.01*weights)) #규제 하이퍼파라미터 값이 0.01

def my_positive_weights(weights): #양수인 가중치만 남김(tf.nn.relu, keras.constraints.nonneg()와 동일)
  return tf.where(weights<0.,tf.zeros_like(weights), weights)

In [ ]:
layer= keras.layers.Dense(30, activation=my_softplus, 
                          kernel_initializer=my_glorot_initializer, 
                          kernel_regularizer=my_l1_regularization, 
                          kernel_constraint=my_positive_weights)

- factor 하이퍼파라미터를 저장하는 l1규제의 클래스 만들기

In [ ]:
class MyL1Regularizer(keras.regularizers.Regularizer):
  def __init__(self, factor):
    self.factor = factor
  def __call__(self, weights):#손실, 층, 모델의 경우 call메서드를 구현해야한다.
    return tf.reduce_sum(tf.abs(self.factor * weights))
  def get_config(self):
    return {'factor':self.factor}

#### 사용자 정의 지표
- 손실과 지표가 개념적으로 다른 것은 아니다.
- 그래서 아까 만든 huber 손실 함수를 지표로 사용해도 잘 동작한다.

In [ ]:
model3.compile(loss='mse', optimizer='nadam', metrics=[create_huber(2.0)])

케라스가 지표를 계산하는 방법은

1. 훈련하는 동안 각 배치에 대해 지표 계산
2. 현재까지의 평균에 더해서 또 평균

ex) 이진분류기
- 첫 번째 배치에서 정밀도 80%(5개를 positive라고 분류했고, 그 중 4개가 True)
- 두 번째 배치에서 정밀도 0%(3개를 positive라고 분류했고, 그 중 0개가 True)
=> 위 방식대로라면 (80+0)/2 = 40%

하지만 옳은 방법이 아님!!
(4+0)/(5+3) => 1/2 => 즉 50%여야한다.

In [ ]:
precision = keras.metrics.Precision()
precision([0,1,1,1,0,1,0,1],[1,1,0,1,0,1,0,1])#첫 번째 배치

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [ ]:
precision([0,1,0,0,1,0,1,1],[1,0,1,1,0,0,0,0]) #두 번째 배치

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

------------
두 번째 배치를 처리한 후 0.5가 되었다.

배치마다 점진적으로 업데이트되기 때문에 이를 <strong>'스트리밍 지표' </strong>또는 '상태가 있는 지표'라고 부른다.

In [ ]:
precision.result() #현재 지푯값 얻기

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [ ]:
precision.variables #변수 확인

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>]

In [ ]:
precision.reset_states() #변수 초기화

##### 스트리밍 지표 만들기
- keras.metrics.Metric 클래스를 상속한다.

In [ ]:
class HuberMetric(keras.metrics.Metric):
  def __init__(self, threshold=1.0, **kwargs):
    super().__init__(**kwargs) #기본 매개변수 처리(ex  dtype)
    self.threshold = threshold
    self.huber_fn = create_huber(threshold)
    self.total = self.add_weight('total', initializer='zeros') #배치마다 업뎃되는 tf.Variable로 관리
    self.count = self.add_weight('count', initializer='zeros')

  def update_state(self, y_true, y_pred, sample_weight=None): #변수 업뎃(이 클래스를 함수처럼 사용할 때 호출된다)
    metric=self.huber_fn(y_true, y_pred)
    self.total.assign_add(tf.reduce_sum(metric))
    self.count.assign_add(tf.cast(tf.size(y_true), tf.float32))

  def result(self): #최종 결과 (평균 손실 값) 반환
    return self.total/self.count

  def get_config(self): #하이퍼파라미터 저장
    base_config=super().get_config()
    return {**base_config, "threshold":self.threshold}

#### 사용자 정의 층 


##### 가중치가 필요없는(Flatten, Pooling, ReLU등) 사용자 정의 층을 만들기
- keras.layers.Lambda 사용 

In [ ]:
exponential_layer = keras.layers.Lambda(lambda x: tf.exp(x))

##### 가중치가 필요한(상태를 가진) 사용자 정의 층 만들기 
- keras.layers.Layer 상속

In [ ]:
class MyDense(keras.layers.Layer):
  def __init__(self, units, activation=None, **kwargs):
    super().__init__(**kwargs) #부모 생성자를 호출해서 매개변수 전달
    self.units= units
    self.activation = keras.activations.get(activation)#적절한 활성화 함수로 바꾸기

  def build(self, batch_input_shape): #가중치마다 add_weight()메서드를 호출해서 층의 변수(tf.Variable)를 만듦 -> 층이 처음 사용될 때 호출
    self.kernel = self.add_weight(
        name='kernel', shape=[batch_input_shape[-1], self.units],#형상이 (n[L-1], n[L])이므로 n[L-1]은 이전 층의 뉴런 개수
        initializer='glorot_normal'
    )

  def call(self, X):#필요한 연산 수행
    return self.activation(X@self.kernel+self.bias)

  def compute_output_shape(self, batch_input_shape):#이 층의 출력 크기
    return tf.TensorShape(batch_input_shpae.as_list()[:-1]+[self.units])

  def get_config(self): #설정 저장
    base_config=super().get_config()
    return {**base_config, 'units':self.units, 'activation':keras.activations.serialize(self.activation)}

##### 여러 입력을 받는 층
- 함수형 API와 서브 클래싱 API에만 사용 가능(시퀀셜 API는 사용 불가) 

In [ ]:
class MyMultiLayer(keras.layers.Layer):
  def call(self, X):
    X1,X2= X
    return [X1+X2, X1*X2, X1/X2]
    
  def compute_output_shape(self, batch_input_shape):
    b1,b2 = batch_input_shape
    return [b1,b1,b1] #올바르게 브로드캐스팅되어야 함

- 훈련과 테스트에서 다른 동작을 하는 층(Dropout, Batch Normalization 등)

In [ ]:
class MyGaussianNoise(keras.layers.Layer):
  def __init__(self, stddev, **kwargs):
    super().__init__(**kwargs)
    self.stddev = stddev

  def call(self, X ,training=True): #training 매개변수 추가
    if training:
      noise = tf.random.nomral(tf.shape(X), stddev= self.stddev)
      return X+noise #가우스 잡음 추가(keras.layers.GaussianNoise와 동일)
    else:
      return X

  def compute_output_shape(self, batch_input_shape):
    return batch_input_shape