<a href="https://colab.research.google.com/github/PingPingE/Learn_ML_DL/blob/main/Practice/Hands_On_ML/ch13-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서플로에서 데이터 적재와 전처리하기
- 메모리 용량에 맞지 않는 큰 규모의 데이터셋으로 딥러닝 시스템을 훈련해야 하는 경우 -> 데이터 API
- 데이터 API로 대규모의 데이터셋을 효율적으로 로드하고 전처리할 수 있다.

# 데이터 API
- 전체적인 데이터 API의 중심에는 <strong>연속된 데이터 샘플인 Dataset</strong> 개념이 있다.
- 일반적으로 <strong>디스크에서 데이터를 점진적으로 읽는</strong> 데이터셋을 사용한다.


In [1]:
import tensorflow as tf

###  Dataset 객체를 만들고 데이터를 읽어 올 위치와 변환 방법을 지정하면 된다

#### from_tensor_slices(): 텐서를 받아 X의 <strong>각 원소가 아이템으로 표현</strong>되는 <strong>tf.data.Dataset</strong>을 만든다. 


In [2]:
X=tf.range(10)
dataset=tf.data.Dataset.from_tensor_slices(X)
dataset # = tf.data.Dataset.range(10)

<TensorSliceDataset shapes: (), types: tf.int32>

In [3]:
for item in dataset: #dataset의 각 원소를 '원소', '아이템', '슬라이스' 등으로 부름
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


### 연쇄 변환

#### repeat 및 batch 메서드

In [4]:
dataset=dataset.repeat(3).batch(7) #원본 dataset의 아이템을 세차례 반복하는 새로운 dataset반환, 7개 그룹으로 묶어서 새로운 dataset 반환
for item in dataset:
  print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


#### map 메서드: <strong>각 아이템</strong>에 변환 적용

In [5]:
dataset=dataset.map(lambda x: x*2) 

In [6]:
for item in dataset:
  print(item)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
tf.Tensor([16 18], shape=(2,), dtype=int32)


#### apply 메서드: <strong>전체</strong>에 변환 적용

In [7]:
dataset=dataset.apply(tf.data.experimental.unbatch()) #unbatch함수를 적용하면 기존의 7개의 정수로 이루어진 배치가 아니라, 하나의 정수 텐서가 된다.

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.


In [8]:
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, sh

#### filter 메서드: 데이터셋 필터링

In [9]:
dataset=dataset.filter(lambda x: x<10)
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


#### take 메서드: 데이터셋에 있는 몇 개의 아이템만 보고 싶을 때

In [10]:
for item in dataset.take(3): #몇 개의 아이템만 보고 싶다면 take 메서드를 사용
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


## 데이터 셔플링
경사 하강법은 훈련 세트에 있는 샘플이 <strong>독립적이고 동일한 분포일 때 최고의 성능</strong>을 발휘한다.
그래서 <strong>shuffle()</strong>메서드를 사용해서 샘플을 섞는다.

### shuffle 메서드
1. 먼저 원본 데이터셋의 처음 아이템을 <strong>buffer_size 개수만큼 추출</strong>해서 버퍼에 채운다. 
2. 그 다음 새로운 아이템이 <strong>요청</strong>되면 <strong>이 버퍼에서 랜덤하게 하나를 꺼내 반환</strong>한다.
3. 그리고 원본 데이터셋에서 새로운 아이템을 <strong>추출</strong>해서 <strong>비워진 버퍼를 또 채운다</strong>.
4. 1~3을 원본 데이터셋의 <strong>모든 아이템이 사용될 때까지 반복</strong>한다. 
5. 그 다음엔 <strong>버퍼가 비워질 때까지</strong> 계속해서 랜덤하게 아이템을 <strong>반환</strong>한다.

In [11]:
dataset=tf.data.Dataset.range(10).repeat(3)#0~9까지 세 번 반복
dataset=dataset.shuffle(buffer_size=5, seed=42).batch(7) #프로그램을 실행할 때마다 셔플링되는 순서를 동일하게 하려면 seed를 부여한다.
for item in dataset:
  print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


In [12]:
for item in dataset.repeat(3):
  print(item)

tf.Tensor([3 5 2 1 8 4 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 7 9 5 0], shape=(7,), dtype=int64)
tf.Tensor([7 4 0 9 6 8 1], shape=(7,), dtype=int64)
tf.Tensor([2 6 6 4 9 8 5], shape=(7,), dtype=int64)
tf.Tensor([7 3], shape=(2,), dtype=int64)
tf.Tensor([2 1 3 5 8 9 4], shape=(7,), dtype=int64)
tf.Tensor([1 0 7 3 5 6 7], shape=(7,), dtype=int64)
tf.Tensor([2 4 9 1 0 3 6], shape=(7,), dtype=int64)
tf.Tensor([0 4 7 5 2 8 6], shape=(7,), dtype=int64)
tf.Tensor([9 8], shape=(2,), dtype=int64)
tf.Tensor([1 4 6 7 5 2 3], shape=(7,), dtype=int64)
tf.Tensor([8 2 0 0 3 5 1], shape=(7,), dtype=int64)
tf.Tensor([4 8 0 6 9 9 2], shape=(7,), dtype=int64)
tf.Tensor([5 3 7 4 1 8 6], shape=(7,), dtype=int64)
tf.Tensor([9 7], shape=(2,), dtype=int64)


### 여러 파일에서 한 줄씩 번갈아 읽기
1. 원본 데이터셋을 <strong>쪼갠다.</strong>
2. 쪼갠 데이터셋을 각각 <strong>csv</strong>로 저장한다.
3. <strong>list</strong>에 2의 파일들을 저장한 <strong>경로</strong>를 모두 담는다.
4. <strong>list_files </strong>함수로 3의 list 원소들을 <strong>섞는다.</strong> 
5. <strong>interleave </strong>메서드를 호출해서 <strong>한 번에 몇 개의 파일을 한 줄씩 번갈아 읽을 것인지</strong> 정한다.

In [13]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
housing = fetch_california_housing()

In [14]:
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)

In [15]:
import pandas as pd
X_train_df=pd.DataFrame(X_train, columns=housing.feature_names)
X_valid_df=pd.DataFrame(X_valid, columns=housing.feature_names)
X_test_df=pd.DataFrame(X_test, columns=housing.feature_names)

In [16]:
X_train_df

MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0      3.5139      31.0  4.591973  ...  3.299331     33.93    -118.35
1      6.2210      52.0  6.571429  ...  2.523810     37.60    -122.40
2      3.4375      46.0  4.044346  ...  2.660754     33.86    -118.19
3      6.3093      19.0  6.037175  ...  3.736803     33.85    -118.09
4      2.9083      14.0  3.648208  ...  3.198697     33.76    -118.00
...       ...       ...       ...  ...       ...       ...        ...
11605  2.7463      18.0  5.122016  ...  3.371353     38.95    -121.08
11606  3.8409      38.0  5.440329  ...  2.249657     32.73    -117.22
11607  2.4207      26.0  4.140541  ...  1.765766     32.85    -117.20
11608  8.1872      52.0  8.268293  ...  2.723577     37.82    -122.23
11609  7.3252      24.0  6.738462  ...  3.171795     34.22    -118.61

[11610 rows x 8 columns]

- train/valid/test csv파일로 만들기

In [17]:
X_train_df.to_csv("my_train.csv", index=False)
X_test_df.to_csv("my_test.csv", index=False)
X_valid_df.to_csv("my_valid.csv", index=False)

- train 데이터 쪼갠 후 각각 따로 저장하기

In [18]:
file_paths=[]#쪼갠 csv파일 path 저장할 list

In [19]:
ls

my_test.csv  my_train.csv  my_valid.csv  sample_data/


In [20]:
mkdir train #쪼갠 csv파일 담을 새로운 디렉토리 생성

In [21]:
X_train.shape

(11610, 8)

In [22]:
#train 데이터 쪼개기
cnt=0
for item in tf.data.Dataset.from_tensor_slices(X_train).batch(100): #100개씩 쪼개서
  file_name=f"train/my_train_{cnt:03}" #해당 path로 저장
  pd.DataFrame(item, columns=housing.feature_names).to_csv(file_name)
  file_paths.append(file_name)
  cnt+=1

- list_files: <strong>파일 경로를 섞은</strong> 데이터셋을 반환(섞는걸 원치 않는다면 shuffle=False 가능)

In [23]:
filepath_dataset=tf.data.Dataset.list_files(file_paths,seed=42)

- interleave: <strong>한 번에 여러 개의 파일을 한 줄씩 번갈아 읽기</strong>(각 파일의 첫 번째 줄은 열의 이름이므로 skip메서드를 사용해서 건너뛴다.)

In [24]:
n_readers=5
dataset=filepath_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers
)

In [25]:
for item in dataset.take(5):
  print(item.numpy())

b'0,"tf.Tensor(3.5335, shape=(), dtype=float64)","tf.Tensor(21.0, shape=(), dtype=float64)","tf.Tensor(3.55, shape=(), dtype=float64)","tf.Tensor(1.05, shape=(), dtype=float64)","tf.Tensor(2719.0, shape=(), dtype=float64)","tf.Tensor(1.9147887323943662, shape=(), dtype=float64)","tf.Tensor(34.04, shape=(), dtype=float64)","tf.Tensor(-118.47, shape=(), dtype=float64)"'
b'0,"tf.Tensor(5.7039, shape=(), dtype=float64)","tf.Tensor(19.0, shape=(), dtype=float64)","tf.Tensor(5.674285714285714, shape=(), dtype=float64)","tf.Tensor(0.9942857142857143, shape=(), dtype=float64)","tf.Tensor(572.0, shape=(), dtype=float64)","tf.Tensor(3.2685714285714287, shape=(), dtype=float64)","tf.Tensor(33.85, shape=(), dtype=float64)","tf.Tensor(-118.1, shape=(), dtype=float64)"'
b'0,"tf.Tensor(3.4375, shape=(), dtype=float64)","tf.Tensor(28.0, shape=(), dtype=float64)","tf.Tensor(4.8584905660377355, shape=(), dtype=float64)","tf.Tensor(1.1666666666666667, shape=(), dtype=float64)","tf.Tensor(1334.0, shape=()

----------------
인터리빙이 잘 동작하려면 <strong>각 파일의 길이가 동일한 것</strong>이 좋다. 그렇지 않으면 가장 긴 파일의 끝은 인터리빙이 되지 않을 것이다.

- 그리고 바이트 스트링으로 저장된다. 그래서 이를 파싱하고 스케일을 조정할 필요가 있다.

#### 실험1: 파일의 길이가 다를 때

In [29]:
tmp_X=tf.range(200)
tmp_list=[]
for e,item in enumerate(tf.data.Dataset.from_tensor_slices(tmp_X).batch(30)):
  file_name=f"tmp_X_{e}"
  pd.DataFrame(item).to_csv(file_name, index=False) #index랑 같이 안나오게 한다
  tmp_list.append(file_name)

In [30]:
tmp_list

['tmp_X_0', 'tmp_X_1', 'tmp_X_2', 'tmp_X_3', 'tmp_X_4', 'tmp_X_5', 'tmp_X_6']

In [28]:
ls

my_test.csv   my_valid.csv  tmp_X_0  tmp_X_2  tmp_X_4  tmp_X_6
my_train.csv  sample_data/  tmp_X_1  tmp_X_3  tmp_X_5  train/


In [ ]:
pd.read_csv("tmp_X_1").shape

(30, 2)

In [ ]:
pd.read_csv("tmp_X_6").shape

(20, 2)

---------------
tmp_X_6.csv만 20개의 샘플을 가지고, 나머진 30개의 샘플을 가진다 <br>
-> 이 때 각 파일 경로를 담은 리스트를 섞고(list_files()) 한 번에 여러 파일을 번갈아 읽게 되면(interleave()) 어떻게 될까?

In [31]:
tmp_dataset=tf.data.Dataset.list_files(tmp_list,seed=423)

In [32]:
for item in tmp_dataset:
  print(item)

tf.Tensor(b'tmp_X_4', shape=(), dtype=string)
tf.Tensor(b'tmp_X_6', shape=(), dtype=string)
tf.Tensor(b'tmp_X_5', shape=(), dtype=string)
tf.Tensor(b'tmp_X_1', shape=(), dtype=string)
tf.Tensor(b'tmp_X_2', shape=(), dtype=string)
tf.Tensor(b'tmp_X_3', shape=(), dtype=string)
tf.Tensor(b'tmp_X_0', shape=(), dtype=string)


In [33]:
n_readers=2
tmp_dataset=tmp_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers
)

In [35]:
dup_cnt=0
for item in tmp_dataset:
  print(item.numpy())

b'180'
b'120'
b'181'
b'121'
b'182'
b'122'
b'183'
b'123'
b'184'
b'124'
b'185'
b'125'
b'186'
b'126'
b'187'
b'127'
b'188'
b'128'
b'189'
b'129'
b'190'
b'130'
b'191'
b'131'
b'192'
b'132'
b'193'
b'133'
b'194'
b'134'
b'195'
b'135'
b'196'
b'136'
b'197'
b'137'
b'198'
b'138'
b'199'
b'139'
b'140'
b'0'
b'141'
b'1'
b'142'
b'2'
b'143'
b'3'
b'144'
b'4'
b'145'
b'5'
b'146'
b'6'
b'147'
b'7'
b'148'
b'8'
b'149'
b'9'
b'10'
b'150'
b'11'
b'151'
b'12'
b'152'
b'13'
b'153'
b'14'
b'154'
b'15'
b'155'
b'16'
b'156'
b'17'
b'157'
b'18'
b'158'
b'19'
b'159'
b'20'
b'160'
b'21'
b'161'
b'22'
b'162'
b'23'
b'163'
b'24'
b'164'
b'25'
b'165'
b'26'
b'166'
b'27'
b'167'
b'28'
b'168'
b'29'
b'169'
b'170'
b'30'
b'171'
b'31'
b'172'
b'32'
b'173'
b'33'
b'174'
b'34'
b'175'
b'35'
b'176'
b'36'
b'177'
b'37'
b'178'
b'38'
b'179'
b'39'
b'40'
b'90'
b'41'
b'91'
b'42'
b'92'
b'43'
b'93'
b'44'
b'94'
b'45'
b'95'
b'46'
b'96'
b'47'
b'97'
b'48'
b'98'
b'49'
b'99'
b'50'
b'100'
b'51'
b'101'
b'52'
b'102'
b'53'
b'103'
b'54'
b'104'
b'55'
b'105'
b'56'
b'106'

---------
마지막 20개는 제대로 셔플링 되지 않은 것을 확인할 수 있다.

#### 실험2: 파일의 길이가 같을 때(위 데이터로)

In [36]:
tmp_X=tf.range(200)
tmp_list=[]
for e,item in enumerate(tf.data.Dataset.from_tensor_slices(tmp_X).batch(20)):
  file_name=f"tmp_X_{e}"
  pd.DataFrame(item).to_csv(file_name,index=False)
  tmp_list.append(file_name)

In [37]:
tmp_list

['tmp_X_0',
 'tmp_X_1',
 'tmp_X_2',
 'tmp_X_3',
 'tmp_X_4',
 'tmp_X_5',
 'tmp_X_6',
 'tmp_X_7',
 'tmp_X_8',
 'tmp_X_9']

In [ ]:
pd.read_csv("tmp_X_1").shape

(20, 2)

In [ ]:
pd.read_csv("tmp_X_9").shape

(20, 2)

-----------
이번엔 모두 20개의 샘플로 동일하게 했다.

In [38]:
tmp_dataset=tf.data.Dataset.list_files(tmp_list,seed=423)

In [39]:
n_readers=2
tmp_dataset=tmp_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers
)

In [40]:
dup_cnt=0
for item in tmp_dataset:
  print(item.numpy())


b'140'
b'180'
b'141'
b'181'
b'142'
b'182'
b'143'
b'183'
b'144'
b'184'
b'145'
b'185'
b'146'
b'186'
b'147'
b'187'
b'148'
b'188'
b'149'
b'189'
b'150'
b'190'
b'151'
b'191'
b'152'
b'192'
b'153'
b'193'
b'154'
b'194'
b'155'
b'195'
b'156'
b'196'
b'157'
b'197'
b'158'
b'198'
b'159'
b'199'
b'20'
b'60'
b'21'
b'61'
b'22'
b'62'
b'23'
b'63'
b'24'
b'64'
b'25'
b'65'
b'26'
b'66'
b'27'
b'67'
b'28'
b'68'
b'29'
b'69'
b'30'
b'70'
b'31'
b'71'
b'32'
b'72'
b'33'
b'73'
b'34'
b'74'
b'35'
b'75'
b'36'
b'76'
b'37'
b'77'
b'38'
b'78'
b'39'
b'79'
b'100'
b'0'
b'101'
b'1'
b'102'
b'2'
b'103'
b'3'
b'104'
b'4'
b'105'
b'5'
b'106'
b'6'
b'107'
b'7'
b'108'
b'8'
b'109'
b'9'
b'110'
b'10'
b'111'
b'11'
b'112'
b'12'
b'113'
b'13'
b'114'
b'14'
b'115'
b'15'
b'116'
b'16'
b'117'
b'17'
b'118'
b'18'
b'119'
b'19'
b'40'
b'160'
b'41'
b'161'
b'42'
b'162'
b'43'
b'163'
b'44'
b'164'
b'45'
b'165'
b'46'
b'166'
b'47'
b'167'
b'48'
b'168'
b'49'
b'169'
b'50'
b'170'
b'51'
b'171'
b'52'
b'172'
b'53'
b'173'
b'54'
b'174'
b'55'
b'175'
b'56'
b'176'
b'57'
b'1

--------------
셔플링이 골고루 잘 되었다~