<a href="https://colab.research.google.com/github/PingPingE/Learn_ML_DL/blob/main/Practice/Hands_On_ML/ch13_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서플로에서 데이터 적재와 전처리하기
- 메모리 용량에 맞지 않는 큰 규모의 데이터셋으로 딥러닝 시스템을 훈련해야 하는 경우 -> 데이터 API
- 데이터 API로 대규모의 데이터셋을 효율적으로 로드하고 전처리할 수 있다.

# 데이터 API
- 전체적인 데이터 API의 중심에는 <strong>연속된 데이터 샘플인 Dataset</strong> 개념이 있다.
- 일반적으로 <strong>디스크에서 데이터를 점진적으로 읽는</strong> 데이터셋을 사용한다.


In [4]:
import tensorflow as tf

###  Dataset 객체를 만들고 데이터를 읽어 올 위치와 변환 방법을 지정하면 된다

#### from_tensor_slices(): 텐서를 받아 X의 <strong>각 원소가 아이템으로 표현</strong>되는 <strong>tf.data.Dataset</strong>을 만든다. 


In [ ]:
X=tf.range(10)
dataset=tf.data.Dataset.from_tensor_slices(X)
dataset # = tf.data.Dataset.range(10)

<TensorSliceDataset shapes: (), types: tf.int32>

In [ ]:
for item in dataset: #dataset의 각 원소를 '원소', '아이템', '슬라이스' 등으로 부름
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


### 연쇄 변환

#### repeat 및 batch 메서드

In [ ]:
dataset=dataset.repeat(3).batch(7) #원본 dataset의 아이템을 세차례 반복하는 새로운 dataset반환, 7개 그룹으로 묶어서 새로운 dataset 반환
for item in dataset:
  print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


#### map 메서드: <strong>각 아이템</strong>에 변환 적용

In [ ]:
dataset=dataset.map(lambda x: x*2) 

In [ ]:
for item in dataset:
  print(item)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
tf.Tensor([16 18], shape=(2,), dtype=int32)


#### apply 메서드: <strong>전체</strong>에 변환 적용

In [ ]:
dataset=dataset.apply(tf.data.experimental.unbatch()) #unbatch함수를 적용하면 기존의 7개의 정수로 이루어진 배치가 아니라, 하나의 정수 텐서가 된다.

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.


In [ ]:
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, sh

#### filter 메서드: 데이터셋 필터링

In [ ]:
dataset=dataset.filter(lambda x: x<10)
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


#### take 메서드: 데이터셋에 있는 몇 개의 아이템만 보고 싶을 때

In [ ]:
for item in dataset.take(3): #몇 개의 아이템만 보고 싶다면 take 메서드를 사용
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


## 데이터 셔플링
경사 하강법은 훈련 세트에 있는 샘플이 <strong>독립적이고 동일한 분포일 때 최고의 성능</strong>을 발휘한다.
그래서 <strong>shuffle()</strong>메서드를 사용해서 샘플을 섞는다.

### shuffle 메서드
1. 먼저 원본 데이터셋의 처음 아이템을 <strong>buffer_size 개수만큼 추출</strong>해서 버퍼에 채운다. 
2. 그 다음 새로운 아이템이 <strong>요청</strong>되면 <strong>이 버퍼에서 랜덤하게 하나를 꺼내 반환</strong>한다.
3. 그리고 원본 데이터셋에서 새로운 아이템을 <strong>추출</strong>해서 <strong>비워진 버퍼를 또 채운다</strong>.
4. 1~3을 원본 데이터셋의 <strong>모든 아이템이 사용될 때까지 반복</strong>한다. 
5. 그 다음엔 <strong>버퍼가 비워질 때까지</strong> 계속해서 랜덤하게 아이템을 <strong>반환</strong>한다.

In [ ]:
dataset=tf.data.Dataset.range(10).repeat(3)#0~9까지 세 번 반복
dataset=dataset.shuffle(buffer_size=5, seed=42).batch(7) #프로그램을 실행할 때마다 셔플링되는 순서를 동일하게 하려면 seed를 부여한다.
for item in dataset:
  print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


In [ ]:
for item in dataset.repeat(3):
  print(item)

tf.Tensor([3 5 2 1 8 4 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 7 9 5 0], shape=(7,), dtype=int64)
tf.Tensor([7 4 0 9 6 8 1], shape=(7,), dtype=int64)
tf.Tensor([2 6 6 4 9 8 5], shape=(7,), dtype=int64)
tf.Tensor([7 3], shape=(2,), dtype=int64)
tf.Tensor([2 1 3 5 8 9 4], shape=(7,), dtype=int64)
tf.Tensor([1 0 7 3 5 6 7], shape=(7,), dtype=int64)
tf.Tensor([2 4 9 1 0 3 6], shape=(7,), dtype=int64)
tf.Tensor([0 4 7 5 2 8 6], shape=(7,), dtype=int64)
tf.Tensor([9 8], shape=(2,), dtype=int64)
tf.Tensor([1 4 6 7 5 2 3], shape=(7,), dtype=int64)
tf.Tensor([8 2 0 0 3 5 1], shape=(7,), dtype=int64)
tf.Tensor([4 8 0 6 9 9 2], shape=(7,), dtype=int64)
tf.Tensor([5 3 7 4 1 8 6], shape=(7,), dtype=int64)
tf.Tensor([9 7], shape=(2,), dtype=int64)


### 여러 파일에서 한 줄씩 번갈아 읽기
1. 원본 데이터셋을 <strong>쪼갠다.</strong>
2. 쪼갠 데이터셋을 각각 <strong>csv</strong>로 저장한다.
3. <strong>list</strong>에 2의 파일들을 저장한 <strong>경로</strong>를 모두 담는다.
4. <strong>list_files </strong>함수로 3의 list 원소들을 <strong>섞는다.</strong> 
5. <strong>interleave </strong>메서드를 호출해서 <strong>한 번에 몇 개의 파일을 한 줄씩 번갈아 읽을 것인지</strong> 정한다.

In [1]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
housing = fetch_california_housing()

In [2]:
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)

In [3]:
import pandas as pd
X_train_df=pd.DataFrame(X_train, columns=housing.feature_names)
X_valid_df=pd.DataFrame(X_valid, columns=housing.feature_names)
X_test_df=pd.DataFrame(X_test, columns=housing.feature_names)

In [ ]:
X_train_df

MedInc  HouseAge   AveRooms  ...  AveOccup  Latitude  Longitude
0      5.7789      13.0   6.324242  ...  3.530303     32.63    -117.03
1      2.4286      32.0   5.029825  ...  2.991228     36.77    -119.83
2      3.6034      16.0   3.220957  ...  1.806378     34.44    -119.82
3      5.0100      20.0  17.546099  ...  2.397163     37.65    -118.99
4      3.3690      25.0   4.610512  ...  2.265499     32.80    -116.96
...       ...       ...        ...  ...       ...       ...        ...
11605  2.6513      42.0   5.674208  ...  2.341629     35.37    -119.03
11606  4.5461      33.0   4.696133  ...  2.709945     33.93    -117.97
11607  6.0487      24.0   7.207080  ...  3.246018     34.26    -118.78
11608  2.5694      27.0   3.143770  ...  2.482428     34.43    -119.72
11609  4.9125      38.0   6.501767  ...  2.236749     32.73    -117.25

[11610 rows x 8 columns]

- train/valid/test csv파일로 만들기

In [19]:
X_train_df.to_csv("my_train.csv", index=False)
X_test_df.to_csv("my_test.csv", index=False)
X_valid_df.to_csv("my_valid.csv", index=False)

- train 데이터 쪼갠 후 각각 따로 저장하기

In [20]:
file_paths=[]#쪼갠 csv파일 path 저장할 list

In [ ]:
ls

my_test.csv  my_train.csv  my_valid.csv  sample_data/


In [21]:
mkdir train #쪼갠 csv파일 담을 새로운 디렉토리 생성

In [ ]:
X_train.shape

(11610, 8)

In [22]:
#train 데이터 쪼개기
cnt=0
for item in tf.data.Dataset.from_tensor_slices(X_train).batch(100): #100개씩 쪼개서
  file_name=f"train/my_train_{cnt:03}" #해당 path로 저장
  pd.DataFrame(item, columns=housing.feature_names).to_csv(file_name)
  file_paths.append(file_name)
  cnt+=1

- list_files: <strong>파일 경로를 섞은</strong> 데이터셋을 반환(섞는걸 원치 않는다면 shuffle=False 가능)

In [23]:
filepath_dataset=tf.data.Dataset.list_files(file_paths,seed=42)

- interleave: <strong>한 번에 여러 개의 파일을 한 줄씩 번갈아 읽기</strong>(각 파일의 첫 번째 줄은 열의 이름이므로 skip메서드를 사용해서 건너뛴다.)

In [24]:
n_readers=5
dataset=filepath_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers
)

In [25]:
for item in dataset.take(5):
  print(item.numpy())

b'0,"tf.Tensor(2.3454, shape=(), dtype=float64)","tf.Tensor(33.0, shape=(), dtype=float64)","tf.Tensor(2.8876404494382024, shape=(), dtype=float64)","tf.Tensor(1.0589887640449438, shape=(), dtype=float64)","tf.Tensor(753.0, shape=(), dtype=float64)","tf.Tensor(2.115168539325843, shape=(), dtype=float64)","tf.Tensor(34.43, shape=(), dtype=float64)","tf.Tensor(-119.72, shape=(), dtype=float64)"'
b'0,"tf.Tensor(1.9911, shape=(), dtype=float64)","tf.Tensor(50.0, shape=(), dtype=float64)","tf.Tensor(5.343675417661098, shape=(), dtype=float64)","tf.Tensor(1.0859188544152745, shape=(), dtype=float64)","tf.Tensor(990.0, shape=(), dtype=float64)","tf.Tensor(2.3627684964200477, shape=(), dtype=float64)","tf.Tensor(37.84, shape=(), dtype=float64)","tf.Tensor(-122.26, shape=(), dtype=float64)"'
b'0,"tf.Tensor(6.5706, shape=(), dtype=float64)","tf.Tensor(9.0, shape=(), dtype=float64)","tf.Tensor(6.961937716262976, shape=(), dtype=float64)","tf.Tensor(1.0934256055363323, shape=(), dtype=float64)","t

----------------
인터리빙이 잘 동작하려면 <strong>각 파일의 길이가 동일한 것</strong>이 좋다. 그렇지 않으면 가장 긴 파일의 끝은 인터리빙이 되지 않을 것이다.

- 그리고 바이트 스트링으로 저장된다. 그래서 이를 파싱하고 스케일을 조정할 필요가 있다.

#### 실험1: 파일의 길이가 다를 때

In [72]:
tmp_X=tf.range(200)
tmp_list=[]
for e,item in enumerate(tf.data.Dataset.from_tensor_slices(tmp_X).batch(30)):
  file_name=f"tmp_X_{e}"
  pd.DataFrame(item).to_csv(file_name)
  tmp_list.append(file_name)

In [73]:
tmp_list

['tmp_X_0', 'tmp_X_1', 'tmp_X_2', 'tmp_X_3', 'tmp_X_4', 'tmp_X_5', 'tmp_X_6']

In [ ]:
ls

my_test.csv   my_valid.csv  tmp_X_0  tmp_X_2  tmp_X_4  tmp_X_6
my_train.csv  sample_data/  tmp_X_1  tmp_X_3  tmp_X_5  train/


In [ ]:
pd.read_csv("tmp_X_1").shape

(30, 2)

In [ ]:
pd.read_csv("tmp_X_6").shape

(20, 2)

---------------
tmp_X_6.csv만 20개의 샘플을 가지고, 나머진 30개의 샘플을 가진다 <br>
-> 이 때 각 파일 경로를 담은 리스트를 섞고(list_files()) 한 번에 여러 파일을 번갈아 읽게 되면(interleave()) 어떻게 될까?

In [74]:
tmp_dataset=tf.data.Dataset.list_files(tmp_list,seed=423)

In [75]:
for item in tmp_dataset:
  print(item)

tf.Tensor(b'tmp_X_4', shape=(), dtype=string)
tf.Tensor(b'tmp_X_6', shape=(), dtype=string)
tf.Tensor(b'tmp_X_5', shape=(), dtype=string)
tf.Tensor(b'tmp_X_1', shape=(), dtype=string)
tf.Tensor(b'tmp_X_2', shape=(), dtype=string)
tf.Tensor(b'tmp_X_3', shape=(), dtype=string)
tf.Tensor(b'tmp_X_0', shape=(), dtype=string)


In [76]:
n_readers=2
tmp_dataset=tmp_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers
)

In [77]:
dup_cnt=0
for item in tmp_dataset:
  tmp=item.numpy().decode('ascii').split(',')
  if tmp[0]==tmp[1]:
    print(tmp)#===뭐가 겹치지
    dup_cnt+=1
print(dup_cnt)

['0', '0']
['1', '1']
['2', '2']
['3', '3']
['4', '4']
['5', '5']
['6', '6']
['7', '7']
['8', '8']
['9', '9']
['10', '10']
['11', '11']
['12', '12']
['13', '13']
['14', '14']
['15', '15']
['16', '16']
['17', '17']
['18', '18']
['19', '19']
['20', '20']
['21', '21']
['22', '22']
['23', '23']
['24', '24']
['25', '25']
['26', '26']
['27', '27']
['28', '28']
['29', '29']
30


---------
겹치는게 30개가 있다.

#### 실험2: 파일의 길이가 같을 때(위 데이터로)

In [53]:
tmp_X=tf.range(200)
tmp_list=[]
for e,item in enumerate(tf.data.Dataset.from_tensor_slices(tmp_X).batch(20)):
  file_name=f"tmp_X_{e}"
  pd.DataFrame(item).to_csv(file_name)
  tmp_list.append(file_name)

In [38]:
tmp_list

['tmp_X_0',
 'tmp_X_1',
 'tmp_X_2',
 'tmp_X_3',
 'tmp_X_4',
 'tmp_X_5',
 'tmp_X_6',
 'tmp_X_7',
 'tmp_X_8',
 'tmp_X_9']

In [39]:
pd.read_csv("tmp_X_1").shape

(20, 2)

In [40]:
pd.read_csv("tmp_X_9").shape

(20, 2)

-----------
이번엔 모두 20개의 샘플로 동일하게 했다.

In [68]:
tmp_dataset=tf.data.Dataset.list_files(tmp_list,seed=423)

In [70]:
n_readers=2
tmp_dataset=tmp_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers
)

In [71]:
dup_cnt=0
for item in tmp_dataset:
  tmp=item.numpy().decode('ascii').split(',')
  if tmp[0]==tmp[1]:
    print(tmp)#===뭐가 겹치지
    dup_cnt+=1
print(dup_cnt)

['0', '0']
['1', '1']
['2', '2']
['3', '3']
['4', '4']
['5', '5']
['6', '6']
['7', '7']
['8', '8']
['9', '9']
['10', '10']
['11', '11']
['12', '12']
['13', '13']
['14', '14']
['15', '15']
['16', '16']
['17', '17']
['18', '18']
['19', '19']
20


--------------
왜 겹치지? -> interleave, TextLineDataset 등의 메서드에 대해 알아봐야겠다.