<a href="https://colab.research.google.com/github/PingPingE/Learn_ML_DL/blob/main/Practice/Hands_On_ML/ch13-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서플로에서 데이터 적재와 전처리하기
- 메모리 용량에 맞지 않는 큰 규모의 데이터셋으로 딥러닝 시스템을 훈련해야 하는 경우 -> 데이터 API
- 데이터 API로 대규모의 데이터셋을 효율적으로 로드하고 전처리할 수 있다.

# 데이터 API
- 전체적인 데이터 API의 중심에는 <strong>연속된 데이터 샘플인 Dataset</strong> 개념이 있다.
- 일반적으로 <strong>디스크에서 데이터를 점진적으로 읽는</strong> 데이터셋을 사용한다.


In [1]:
import tensorflow as tf

###  Dataset 객체를 만들고 데이터를 읽어 올 위치와 변환 방법을 지정하면 된다

#### from_tensor_slices(): 텐서를 받아 X의 <strong>각 원소가 아이템으로 표현</strong>되는 <strong>tf.data.Dataset</strong>을 만든다. 


In [ ]:
X=tf.range(10)
dataset=tf.data.Dataset.from_tensor_slices(X)
dataset # = tf.data.Dataset.range(10)

<TensorSliceDataset shapes: (), types: tf.int32>

In [ ]:
for item in dataset: #dataset의 각 원소를 '원소', '아이템', '슬라이스' 등으로 부름
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


### 연쇄 변환

#### repeat 및 batch 메서드

In [ ]:
dataset=dataset.repeat(3).batch(7) #원본 dataset의 아이템을 세차례 반복하는 새로운 dataset반환, 7개 그룹으로 묶어서 새로운 dataset 반환
for item in dataset:
  print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


#### map 메서드: <strong>각 아이템</strong>에 변환 적용

In [ ]:
dataset=dataset.map(lambda x: x*2) 

In [ ]:
for item in dataset:
  print(item)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
tf.Tensor([16 18], shape=(2,), dtype=int32)


#### apply 메서드: <strong>전체</strong>에 변환 적용

In [ ]:
dataset=dataset.apply(tf.data.experimental.unbatch()) #unbatch함수를 적용하면 기존의 7개의 정수로 이루어진 배치가 아니라, 하나의 정수 텐서가 된다.

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.


In [ ]:
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, sh

#### filter 메서드: 데이터셋 필터링

In [ ]:
dataset=dataset.filter(lambda x: x<10)
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


#### take 메서드: 데이터셋에 있는 몇 개의 아이템만 보고 싶을 때

In [ ]:
for item in dataset.take(3): #몇 개의 아이템만 보고 싶다면 take 메서드를 사용
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


## 데이터 셔플링
경사 하강법은 훈련 세트에 있는 샘플이 <strong>독립적이고 동일한 분포일 때 최고의 성능</strong>을 발휘한다.
그래서 <strong>shuffle()</strong>메서드를 사용해서 샘플을 섞는다.

### shuffle 메서드
1. 먼저 원본 데이터셋의 처음 아이템을 <strong>buffer_size 개수만큼 추출</strong>해서 버퍼에 채운다. 
2. 그 다음 새로운 아이템이 <strong>요청</strong>되면 <strong>이 버퍼에서 랜덤하게 하나를 꺼내 반환</strong>한다.
3. 그리고 원본 데이터셋에서 새로운 아이템을 <strong>추출</strong>해서 <strong>비워진 버퍼를 또 채운다</strong>.
4. 1~3을 원본 데이터셋의 <strong>모든 아이템이 사용될 때까지 반복</strong>한다. 
5. 그 다음엔 <strong>버퍼가 비워질 때까지</strong> 계속해서 랜덤하게 아이템을 <strong>반환</strong>한다.

In [ ]:
dataset=tf.data.Dataset.range(10).repeat(3)#0~9까지 세 번 반복
dataset=dataset.shuffle(buffer_size=5, seed=42).batch(7) #프로그램을 실행할 때마다 셔플링되는 순서를 동일하게 하려면 seed를 부여한다.
for item in dataset:
  print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


In [ ]:
for item in dataset.repeat(3):
  print(item)

tf.Tensor([3 5 2 1 8 4 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 7 9 5 0], shape=(7,), dtype=int64)
tf.Tensor([7 4 0 9 6 8 1], shape=(7,), dtype=int64)
tf.Tensor([2 6 6 4 9 8 5], shape=(7,), dtype=int64)
tf.Tensor([7 3], shape=(2,), dtype=int64)
tf.Tensor([2 1 3 5 8 9 4], shape=(7,), dtype=int64)
tf.Tensor([1 0 7 3 5 6 7], shape=(7,), dtype=int64)
tf.Tensor([2 4 9 1 0 3 6], shape=(7,), dtype=int64)
tf.Tensor([0 4 7 5 2 8 6], shape=(7,), dtype=int64)
tf.Tensor([9 8], shape=(2,), dtype=int64)
tf.Tensor([1 4 6 7 5 2 3], shape=(7,), dtype=int64)
tf.Tensor([8 2 0 0 3 5 1], shape=(7,), dtype=int64)
tf.Tensor([4 8 0 6 9 9 2], shape=(7,), dtype=int64)
tf.Tensor([5 3 7 4 1 8 6], shape=(7,), dtype=int64)
tf.Tensor([9 7], shape=(2,), dtype=int64)


### 여러 파일에서 한 줄씩 번갈아 읽기
1. 원본 데이터셋을 <strong>쪼갠다.</strong>
2. 쪼갠 데이터셋을 각각 <strong>csv</strong>로 저장한다.
3. <strong>list</strong>에 2의 파일들을 저장한 <strong>경로</strong>를 모두 담는다.
4. <strong>list_files </strong>함수로 3의 list 원소들을 <strong>섞는다.</strong> 
5. <strong>interleave </strong>메서드를 호출해서 <strong>한 번에 몇 개의 파일을 한 줄씩 번갈아 읽을 것인지</strong> 정한다.

In [20]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
housing = fetch_california_housing()

In [21]:
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)

In [22]:
import pandas as pd
X_train_df=pd.DataFrame(X_train, columns=housing.feature_names)
X_valid_df=pd.DataFrame(X_valid, columns=housing.feature_names)
X_test_df=pd.DataFrame(X_test, columns=housing.feature_names)

In [23]:
X_train_df

MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0      9.2298      25.0  7.237676  ...  2.790493     37.31    -122.05
1      4.7500      52.0  4.771812  ...  2.315436     37.79    -122.47
2      4.1563       4.0  5.645833  ...  2.723214     34.66    -120.48
3      3.5200      32.0  5.897297  ...  3.032432     36.96    -122.03
4      2.5200      37.0  4.251623  ...  1.870130     37.88    -122.27
...       ...       ...       ...  ...       ...       ...        ...
11605  3.9423      39.0  5.509653  ...  2.583012     37.15    -122.13
11606  1.5491       9.0  5.641834  ...  2.306590     34.13    -116.35
11607  2.0441      15.0  4.064639  ...  2.163498     35.06    -118.15
11608  3.0208      34.0  4.500000  ...  2.772300     32.75    -117.06
11609  1.6045      36.0  3.822951  ...  3.565574     35.76    -119.25

[11610 rows x 8 columns]

- train/valid/test csv파일로 만들기

In [24]:
X_train_df.to_csv("my_train.csv", index=False)
X_test_df.to_csv("my_test.csv", index=False)
X_valid_df.to_csv("my_valid.csv", index=False)

- train 데이터 쪼갠 후 각각 따로 저장하기

In [9]:
file_paths=[]#쪼갠 csv파일 path 저장할 list

In [10]:
ls

sample_data/


In [11]:
mkdir train #쪼갠 csv파일 담을 새로운 디렉토리 생성

In [25]:
X_train.shape

(11610, 8)

In [31]:
#train 데이터 쪼개기
cnt=0
for item in tf.data.Dataset.from_tensor_slices(X_train).batch(100): #100개씩 쪼개서
  file_name=f"train/my_train_{cnt:03}" #해당 path로 저장
  pd.DataFrame(item.numpy(),columns=housing.feature_names).to_csv(file_name,index=False)#numpy배열로 바꿔서 저장
  file_paths.append(file_name)
  cnt+=1

- list_files: <strong>파일 경로를 섞은</strong> 데이터셋을 반환(섞는걸 원치 않는다면 shuffle=False 가능)

In [32]:
filepath_dataset=tf.data.Dataset.list_files(file_paths,seed=42)

- interleave: <strong>한 번에 여러 개의 파일을 한 줄씩 번갈아 읽기</strong>(각 파일의 첫 번째 줄은 열의 이름이므로 skip메서드를 사용해서 건너뛴다.)

In [33]:
n_readers=5
dataset=filepath_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers
)

In [ ]:
#텐서로 저장했을 때
for item in dataset.take(5):
  print(item.numpy())

b'0,"tf.Tensor(3.5335, shape=(), dtype=float64)","tf.Tensor(21.0, shape=(), dtype=float64)","tf.Tensor(3.55, shape=(), dtype=float64)","tf.Tensor(1.05, shape=(), dtype=float64)","tf.Tensor(2719.0, shape=(), dtype=float64)","tf.Tensor(1.9147887323943662, shape=(), dtype=float64)","tf.Tensor(34.04, shape=(), dtype=float64)","tf.Tensor(-118.47, shape=(), dtype=float64)"'
b'0,"tf.Tensor(5.7039, shape=(), dtype=float64)","tf.Tensor(19.0, shape=(), dtype=float64)","tf.Tensor(5.674285714285714, shape=(), dtype=float64)","tf.Tensor(0.9942857142857143, shape=(), dtype=float64)","tf.Tensor(572.0, shape=(), dtype=float64)","tf.Tensor(3.2685714285714287, shape=(), dtype=float64)","tf.Tensor(33.85, shape=(), dtype=float64)","tf.Tensor(-118.1, shape=(), dtype=float64)"'
b'0,"tf.Tensor(3.4375, shape=(), dtype=float64)","tf.Tensor(28.0, shape=(), dtype=float64)","tf.Tensor(4.8584905660377355, shape=(), dtype=float64)","tf.Tensor(1.1666666666666667, shape=(), dtype=float64)","tf.Tensor(1334.0, shape=()

In [34]:
#넘파이로 저장했을 때
for item in dataset.take(5):
  print(item.numpy())

b'4.4094,52.0,5.158227848101266,1.0332278481012658,1594.0,2.5221518987341773,37.76,-122.48'
b'3.125,42.0,4.968468468468468,1.0157657657657657,989.0,2.2274774774774775,37.94,-122.34'
b'2.9871,52.0,3.7246376811594204,1.046583850931677,2062.0,2.1345755693581783,37.79,-122.41'
b'5.7452,14.0,7.0285087719298245,1.019736842105263,1439.0,3.155701754385965,38.44,-121.34'
b'6.3052,31.0,5.292096219931271,0.9037800687285223,1493.0,2.5652920962199315,37.34,-122.01'


----------------
인터리빙이 잘 동작하려면 <strong>각 파일의 길이가 동일한 것</strong>이 좋다. 그렇지 않으면 가장 긴 파일의 끝은 인터리빙이 되지 않을 것이다.

- 그리고 바이트 스트링으로 저장된다. 그래서 이를 파싱하고 스케일을 조정할 필요가 있다.

#### 실험1: 파일의 길이가 다를 때

In [ ]:
tmp_X=tf.range(200)
tmp_list=[]
for e,item in enumerate(tf.data.Dataset.from_tensor_slices(tmp_X).batch(30)):
  file_name=f"tmp_X_{e}"
  pd.DataFrame(item).to_csv(file_name, index=False) #index랑 같이 안나오게 한다
  tmp_list.append(file_name)

In [ ]:
tmp_list

['tmp_X_0', 'tmp_X_1', 'tmp_X_2', 'tmp_X_3', 'tmp_X_4', 'tmp_X_5', 'tmp_X_6']

In [ ]:
ls

my_test.csv   my_valid.csv  tmp_X_0  tmp_X_2  tmp_X_4  tmp_X_6
my_train.csv  sample_data/  tmp_X_1  tmp_X_3  tmp_X_5  train/


In [ ]:
pd.read_csv("tmp_X_1").shape

(30, 2)

In [ ]:
pd.read_csv("tmp_X_6").shape

(20, 2)

---------------
tmp_X_6.csv만 20개의 샘플을 가지고, 나머진 30개의 샘플을 가진다 <br>
-> 이 때 각 파일 경로를 담은 리스트를 섞고(list_files()) 한 번에 여러 파일을 번갈아 읽게 되면(interleave()) 어떻게 될까?

In [ ]:
tmp_dataset=tf.data.Dataset.list_files(tmp_list,seed=423)

In [ ]:
for item in tmp_dataset:
  print(item)

tf.Tensor(b'tmp_X_4', shape=(), dtype=string)
tf.Tensor(b'tmp_X_6', shape=(), dtype=string)
tf.Tensor(b'tmp_X_5', shape=(), dtype=string)
tf.Tensor(b'tmp_X_1', shape=(), dtype=string)
tf.Tensor(b'tmp_X_2', shape=(), dtype=string)
tf.Tensor(b'tmp_X_3', shape=(), dtype=string)
tf.Tensor(b'tmp_X_0', shape=(), dtype=string)


In [ ]:
n_readers=2
tmp_dataset=tmp_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers
)

In [ ]:
dup_cnt=0
for item in tmp_dataset:
  print(item.numpy())

b'180'
b'120'
b'181'
b'121'
b'182'
b'122'
b'183'
b'123'
b'184'
b'124'
b'185'
b'125'
b'186'
b'126'
b'187'
b'127'
b'188'
b'128'
b'189'
b'129'
b'190'
b'130'
b'191'
b'131'
b'192'
b'132'
b'193'
b'133'
b'194'
b'134'
b'195'
b'135'
b'196'
b'136'
b'197'
b'137'
b'198'
b'138'
b'199'
b'139'
b'140'
b'0'
b'141'
b'1'
b'142'
b'2'
b'143'
b'3'
b'144'
b'4'
b'145'
b'5'
b'146'
b'6'
b'147'
b'7'
b'148'
b'8'
b'149'
b'9'
b'10'
b'150'
b'11'
b'151'
b'12'
b'152'
b'13'
b'153'
b'14'
b'154'
b'15'
b'155'
b'16'
b'156'
b'17'
b'157'
b'18'
b'158'
b'19'
b'159'
b'20'
b'160'
b'21'
b'161'
b'22'
b'162'
b'23'
b'163'
b'24'
b'164'
b'25'
b'165'
b'26'
b'166'
b'27'
b'167'
b'28'
b'168'
b'29'
b'169'
b'170'
b'30'
b'171'
b'31'
b'172'
b'32'
b'173'
b'33'
b'174'
b'34'
b'175'
b'35'
b'176'
b'36'
b'177'
b'37'
b'178'
b'38'
b'179'
b'39'
b'40'
b'90'
b'41'
b'91'
b'42'
b'92'
b'43'
b'93'
b'44'
b'94'
b'45'
b'95'
b'46'
b'96'
b'47'
b'97'
b'48'
b'98'
b'49'
b'99'
b'50'
b'100'
b'51'
b'101'
b'52'
b'102'
b'53'
b'103'
b'54'
b'104'
b'55'
b'105'
b'56'
b'106'

---------
마지막 20개는 제대로 셔플링 되지 않은 것을 확인할 수 있다.

#### 실험2: 파일의 길이가 같을 때(위 데이터로)

In [ ]:
tmp_X=tf.range(200)
tmp_list=[]
for e,item in enumerate(tf.data.Dataset.from_tensor_slices(tmp_X).batch(20)):
  file_name=f"tmp_X_{e}"
  pd.DataFrame(item).to_csv(file_name,index=False)
  tmp_list.append(file_name)

In [ ]:
tmp_list

['tmp_X_0',
 'tmp_X_1',
 'tmp_X_2',
 'tmp_X_3',
 'tmp_X_4',
 'tmp_X_5',
 'tmp_X_6',
 'tmp_X_7',
 'tmp_X_8',
 'tmp_X_9']

In [ ]:
pd.read_csv("tmp_X_1").shape

(20, 2)

In [ ]:
pd.read_csv("tmp_X_9").shape

(20, 2)

-----------
이번엔 모두 20개의 샘플로 동일하게 했다.

In [ ]:
tmp_dataset=tf.data.Dataset.list_files(tmp_list,seed=423)

In [ ]:
n_readers=2
tmp_dataset=tmp_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers
)

In [ ]:
dup_cnt=0
for item in tmp_dataset:
  print(item.numpy())


b'140'
b'180'
b'141'
b'181'
b'142'
b'182'
b'143'
b'183'
b'144'
b'184'
b'145'
b'185'
b'146'
b'186'
b'147'
b'187'
b'148'
b'188'
b'149'
b'189'
b'150'
b'190'
b'151'
b'191'
b'152'
b'192'
b'153'
b'193'
b'154'
b'194'
b'155'
b'195'
b'156'
b'196'
b'157'
b'197'
b'158'
b'198'
b'159'
b'199'
b'20'
b'60'
b'21'
b'61'
b'22'
b'62'
b'23'
b'63'
b'24'
b'64'
b'25'
b'65'
b'26'
b'66'
b'27'
b'67'
b'28'
b'68'
b'29'
b'69'
b'30'
b'70'
b'31'
b'71'
b'32'
b'72'
b'33'
b'73'
b'34'
b'74'
b'35'
b'75'
b'36'
b'76'
b'37'
b'77'
b'38'
b'78'
b'39'
b'79'
b'100'
b'0'
b'101'
b'1'
b'102'
b'2'
b'103'
b'3'
b'104'
b'4'
b'105'
b'5'
b'106'
b'6'
b'107'
b'7'
b'108'
b'8'
b'109'
b'9'
b'110'
b'10'
b'111'
b'11'
b'112'
b'12'
b'113'
b'13'
b'114'
b'14'
b'115'
b'15'
b'116'
b'16'
b'117'
b'17'
b'118'
b'18'
b'119'
b'19'
b'40'
b'160'
b'41'
b'161'
b'42'
b'162'
b'43'
b'163'
b'44'
b'164'
b'45'
b'165'
b'46'
b'166'
b'47'
b'167'
b'48'
b'168'
b'49'
b'169'
b'50'
b'170'
b'51'
b'171'
b'52'
b'172'
b'53'
b'173'
b'54'
b'174'
b'55'
b'175'
b'56'
b'176'
b'57'
b'1

--------------
셔플링이 골고루 잘 되었다~

## 데이터 전처리

In [111]:
X_mean,X_std=X_train.mean(axis=0), X_train.std(axis=0) #각 특성의 평균과 표준편차(8개의 실수를 가진 1d배열)
n_inputs=8

In [39]:
X_mean

array([ 3.88766019e+00,  2.85695090e+01,  5.42851353e+00,  1.09514096e+00,
        1.43068114e+03,  3.15727214e+00,  3.56134238e+01, -1.19552316e+02])

In [40]:
X_std

array([1.90668478e+00, 1.25217688e+01, 2.43212793e+00, 4.26016843e-01,
       1.15023060e+03, 1.37834628e+01, 2.12596383e+00, 1.99297472e+00])

- 바이트 스트링 값 파싱 및 스케일링하는 함수

In [116]:
def preprocess(line):#csv 한 라인을 받아 파싱한다.
  print("====from: ", line)
  defs=[0.]*n_inputs #초깃값 설정(실수 형태, 누락된 값은 0.으로 채움)
  fields=tf.io.decode_csv(line, record_defaults=defs)#파싱할 라인과 초깃값 지정
  print("====after decoding: ",fields)
  
  #decode_csv는  열마다 한 개씩 스칼라 텐서의 리스트 반환한다. ->모든 텐서를 쌓아 1d배열로 만들어야 한다.
  x=tf.stack(fields[:]) 
  y=tf.stack(fields[:])
  return (x-X_mean)/X_std, y#스케일링

In [117]:
for item in dataset.take(1):
 print("===to: ",preprocess(item.numpy()))

====from:  b'5.2809,28.0,6.872727272727273,1.018181818181818,752.0,2.278787878787879,36.82,-119.82'
====after decoding:  [<tf.Tensor: shape=(), dtype=float32, numpy=5.2809>, <tf.Tensor: shape=(), dtype=float32, numpy=28.0>, <tf.Tensor: shape=(), dtype=float32, numpy=6.8727274>, <tf.Tensor: shape=(), dtype=float32, numpy=1.0181818>, <tf.Tensor: shape=(), dtype=float32, numpy=752.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2.2787879>, <tf.Tensor: shape=(), dtype=float32, numpy=36.82>, <tf.Tensor: shape=(), dtype=float32, numpy=-119.82>]
===to:  (<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([ 0.7307132 , -0.04548156,  0.5938067 , -0.1806481 , -0.5900392 ,
       -0.06373466,  0.5675436 , -0.13431427], dtype=float32)>, <tf.Tensor: shape=(8,), dtype=float32, numpy=
array([   5.2809   ,   28.       ,    6.8727274,    1.0181818,
        752.       ,    2.2787879,   36.82     , -119.82     ],
      dtype=float32)>)


### 데이터 적재 + 전처리

<img src="https://pic1.zhimg.com/v2-bbd864e5a99678090a5bb8567032c9c0_b.jpg"/>

In [ ]:
def csv_reader_dataset(filepaths,repeat=1,n_readers=5,n_read_threads=None, shuffle_buffer_size=10000, n_parse_threads=5, batch_size=32):
  dataset=tf.data.Dataset.list_files(filepaths).repeat(repeat)
  dataset=dataset.interleave(
      lambda filepath: tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_readers, num_parallel_calls=n_read_threads
  )
  dataset=dataset.shuffle(shuffle_buffer_size)
  dataset=dataset.map(preprocess, num_parallel_calls=num_parse_threads)
  return dataset.batch(batch_size).prefetch(1) #prefetch(1)을 호출하면 작업을 하는 동안 다음 배치를 준비함(미리 읽고 전처리)->성능 향상에 큰 기여


데이터 셋을 
- 셔플링하고
- 전처리하고
- 효율적으로 적재

<img src="https://pic4.zhimg.com/80/v2-3be19d36338ad366370616e51ee0ecbb_1440w.jpg" width=50% height=50%/>

-----------
- prefetch: GPU가 작업을 하는 동안 CPU는 다음 배치를 미리 준비하게 한다.
- 만약 멀티스레드로 데이터를 적재하고 전처리하면 GPU를 100% 활용할 수 있게된다.
- 메모리 크기가 충분하다면 메모리에 모두 데이터셋을 캐싱할 수 있도록 cache()메서드를 사용해서 훈련 속도를 높일 수도 있다.



여기까지가 데이터 API를 사용해서 강력한 입력 파이프라인을 만드는 방법.<br>
-> 대규모의 복잡한(이미지,오디오 등) 데이터 구조라면 <strong>TFRecord</strong>를 사용해야한다.